import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar 從 content/ 目錄自動生成。
 * TASK-20260418-04 會在 content/{book-slug}/ 下產生章節檔，
 * autogenerated 會依據檔名前綴 (01-xxx, 02-xxx ...) 自動排序。
 */
const sidebars: SidebarsConfig = {
  contentSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
